apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::122283693125:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1F2WXDAZ91W36
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::122283693125:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-02T17:49:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1446"
  uid: 6c988013-1685-4908-a2c2-304f44e4698e
